// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdO8OUr6pmJwyLtS4Ujl_rXcB-TXU1xsQ',
    appId: '1:183316760387:web:608660b525655a378611f6',
    messagingSenderId: '183316760387',
    projectId: 'noteapp-a8846',
    authDomain: 'noteapp-a8846.firebaseapp.com',
    storageBucket: 'noteapp-a8846.appspot.com',
    measurementId: 'G-QESCBQ68V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_8XhM3FjlQ1Yy19n6_JL1D7LYzA6_m8',
    appId: '1:183316760387:android:096b0640c65473978611f6',
    messagingSenderId: '183316760387',
    projectId: 'noteapp-a8846',
    storageBucket: 'noteapp-a8846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2Zd54pUBSXe9stO8SftqHg30pRZHpjU',
    appId: '1:183316760387:ios:70e2b32f4fa32ca38611f6',
    messagingSenderId: '183316760387',
    projectId: 'noteapp-a8846',
    storageBucket: 'noteapp-a8846.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
}
